<?php
session_start();
include_once("../../config.php");
include_once("../../includes/wall.php");
if(isset($_SESSION['user_id']))
{
	$db->connect();
	print_wall($_SESSION['user_id']);
	$db->close();
}
?>
